# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9

CFLAGS    += -fstack-protector-strong -g
CXXFLAGS  += -fstack-protector-strong -g -std=c++20 -Icommon
LIBS      += -lnds9d
